config/routes.rb
Rails.application.routes.draw do
	get 'dashboard/index'
	root 'dashboard#index', as: 'dashboard'
	get 'appointments/new', as: 'new'
	get 'appointments/delete_all', as: 'delete_all'
	resources :appointments
	Rails.application.routes.draw do
		namespace :api do
			namespace :v1 do
				resources :appointments
			end
		end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	end
	get "/appointments/recursive/:id", to: "appointments#recursive", as: "recursive"
	post 'appointments/create_recursive', as: 'create_recursive'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
    def self.search(search)
	  if search
	    self.where("title like ?", "%#{search}%")
	  else
	    self.all
	  end
		end

	validate :end_after_start
	validates :start_time, :end_time, :presence => true

	private
	def end_after_start
		return if end_time.blank? || start_time.blank?

		if end_time < start_time || end_time == start_time
			errors.add(:end_time, "must be after the start time")
		end
	end

end

app/controllers/api/v1/appointments_controller.rb
class Api::V1::AppointmentsController < ApplicationController

	def new
		@appointment = Appointment.new
	end

	def index
		@appointments = Appointment.all
		render json: @appointments
	end

	def show
		render json: @appointment = Appointment.find(params[:id])
	end

	def delete_all
		@appointments = Appointment.all
		@appointments.each do |appointment|
		 	appointment.destroy
	    end 
		redirect_to dashboard_path
	end

	def create
		@appointment = Appointment.new(appointment_params)
		if @appointment.save
			render json: @appointment, status: :created, location: api_v1_appointment_url(@appointment)
		else
			render json: @appointment.errors, status: :unprocessable_entity
		end
	end

	def update
		if @appointment.update(appointment_params)
			render json: @appointment
		else
			render json: @appointment.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@appointment = Appointment.find(params[:id])
		@appointment.destroy
	end

  	def recursive
  		@appointment = Appointment.find(params[:id])
  	end

  	def create_recursive
	i = 0
		loop do
		  i += 1
		  if params[:type] == '1'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+7.day
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  if params[:type] == '2'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+1.month
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  if params[:type] == '3'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+1.year
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  @appointment = Appointment.new(appointment_params)
			if @appointment.save

			  else
			    render 'recursive'
			    break
			  end
		  if i == params[:length]["{:required=>true}"].to_i
		    break      
		  end
		end 
		redirect_to dashboard_path
  	end




	def edit
		@appointment = Appointment.find(params[:id])
	end



	private
	  def appointment_params
	    params.require(:appointment).permit(:title, :comment, :date, :start_time, :end_time)
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
require 'active_support/core_ext'
class AppointmentsController < ApplicationController
	def new
		@appointment = Appointment.new
	end

	def delete_all
		@appointments = Appointment.all
		@appointments.each do |appointment|
		 	appointment.destroy
	    end 
		redirect_to dashboard_path
	end

	def show
      @appointment = Appointment.find(params[:id])
  	end

  	def recursive
  		@appointment = Appointment.find(params[:id])
  	end

  	def create_recursive
	i = 0
		loop do
		  i += 1
		  if params[:type] == '1'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+7.day
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  if params[:type] == '2'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+1.month
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  if params[:type] == '3'
		  	params[:appointment][:date] = params[:appointment][:date].to_time.to_i+1.year
		  	params[:appointment][:date] = Time.at(params[:appointment][:date]).strftime("%Y/%m/%d")
		  	
		  end
		  @appointment = Appointment.new(appointment_params)
			if @appointment.save

			  else
			    render 'recursive'
			    break
			  end
		  if i == params[:length]["{:required=>true}"].to_i
		    break      
		  end
		end 
		redirect_to dashboard_path
  	end

	def create
	  @appointment = Appointment.new(appointment_params)
	  if @appointment.save
	    redirect_to @appointment
	  else
	    render 'new'
	  end
	end

	def destroy
	    @appointment = Appointment.find(params[:id])
	    @appointment.destroy
	 	redirect_to dashboard_path
  	end

	def edit
		@appointment = Appointment.find(params[:id])
	end

	 def update
	 	@appointment = Appointment.find(params[:id])
		 if @appointment.update(appointment_params)
		 redirect_to @appointment
	 else
		 render 'edit'
	 end
	 end

	private
	  def appointment_params
	    params.require(:appointment).permit(:title, :comment, :date, :start_time, :end_time)
	  end
end

app/controllers/controller_test_controller.rb
class ControllerTestController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@appointments = Appointment.search(params[:search])
	end
end

app/controllers/tes_tcontroller_controller.rb
class TesTcontrollerController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/controller_test_helper.rb
module ControllerTestHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tes_tcontroller_helper.rb
module TesTcontrollerHelper
end

app/views/appointments/edit.html.erb
  <div class="page_form">
    <h1>Edit appointment</h1>
  <%= form_with(model: @appointment, local: true) do |form| %>
      <% if @appointment.errors.any? %>
        <div id="error_explanation">

          <ul>
            <% @appointment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :date %><br>
      <%= date_field(:appointment, :date) %>
    </p>

    <p>
      <%= form.label :Start %><br>
      <%= time_field(:appointment, :start_time) %>
    </p>

    <p>
      <%= form.label :End %><br>
      <%= time_field(:appointment, :end_time) %>
    </p>

    <p>
      <%= form.label :comment %><br>
      <%= form.text_area :comment %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Back', dashboard_path %>
  </div>

app/views/appointments/new.html.erb
<div class="page_form">
<%= form_with scope: :appointment, url: appointments_path, local: true do |form| %>
 <% if @appointment.errors.any? %>
    <div id="error_explanation">

      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title%>
  </p>
  <p>
    <%= form.label :date %><br>
    <%= date_field(:appointment, :date) %>
  </p>

  <p>
    <%= form.label :Start %><br>
    <%= time_field(:appointment, :start_time) %>
  </p>

  <p>
    <%= form.label :End %><br>
    <%= time_field(:appointment, :end_time) %>
  </p>

  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dashboard_path %>
</div>

app/views/appointments/recursive.html.erb
<div class="page_form">
<%= form_with scope: :appointment, url: create_recursive_path, local: true do |form| %>
 <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@appointment.errors.count, "error") %> prohibited
        this appointment from being saved:
      </h2>
      <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title%>
  </p>
  <p>
    <%= form.label :date %><br>
    <%= date_field(:appointment, :date, readonly: true) %>
  </p>

  <p>
    <%= form.label :Start %><br>
    <%= time_field(:appointment, :start_time) %>
  </p>

  <p>
    <%= form.label :Type %><br>
    <%= select_tag(:type, options_for_select([['Weekly', 1], ['Monthly', 2], ['Yearly', 3]])) %>
  </p>

  <p>
    <%= form.label :Length %><br>
    <%= number_field :length , :required => true%>
  </p>

  <p>
    <%= form.label :End %><br>
    <%= time_field(:appointment, :end_time) %>
  </p>
 
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dashboard_path %>
</div>

app/views/appointments/show.html.erb
<div class="show">
  <div style="margin-top:5px;margin-bottom:10px;">
    <table border = "0px" bordercolor="Green"  width="200px">
      <tr>
        <td style="text-align:left"><b>Title:</b></td>
        <td><%= @appointment.title %></td>
      </tr>
      <tr>
        <td style="text-align:left"><b>Comment:</b></td>
        <td><%= @appointment.comment %></td>
      </tr>
      <tr>
        <td style="text-align:left"><b>Date:</b></td>
        <td><%= @appointment.date %></td>
      </tr>
      <tr>
        <td style="text-align:left"><b>Start:</b></td>
        <td><%= @appointment.start_time.to_formatted_s(:time) %></td>
      </tr>
      <tr>
        <td style="text-align:left"><b>End:</b></td>
        <td><%= @appointment.end_time.to_formatted_s(:time) %></td>
      </tr>
    </table>
  </div>
  <b><%= link_to 'Back', dashboard_path %></b>
</div>

app/views/dashboard/index.html.erb
<div id="calendar" style="margin-top: 150px;"></div>
<div style = "margin-top: 7%; margin-left: 1%;">
  <h1>Listing Appointments</h1>
  <div class="container" >
  	<div class="row" style="height:250px;overflow:scroll;overflow:auto;margin-bottom:50px;margin-top:20px">
  		  <div class="col-md-12">
          <div class="table-responsive">
            <table id="scrolltable" class="table table-bordred table-striped">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Comment</th>
                  <th>Date</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th colspan="4"> Action</th>
                  <th><%= link_to 'Delete All', delete_all_path,
                        data: { confirm: 'Are you sure?' } %></th>
                </tr>
              </thead>
              <tbody id="parent">
            <% @appointments.each do |appointment| %>
              <tr>
                <td><%= appointment.title %></td>
                <td><%= appointment.comment %></td>
                <td><%= appointment.date %></td>
                <td><%= appointment.start_time.to_formatted_s(:time) %></td>
                <td><%= appointment.end_time.to_formatted_s(:time) %></td>
                <td><%= link_to 'Show', appointments_path+"/"+appointment.id.to_s %></td>
                <td><%= link_to 'Delete', appointment_path(appointment),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
                <td><%= link_to 'Repeat', recursive_path(appointment) %></td>
                <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
                <td></td>
              </tr>
            <% end %>

            </tbody>
        </table>

        </div>
      </div>
    </div>
  </div>
</div>


<script>
   var evs = [];


       $('#parent').children('tr').each(function () {
           var titleObj = $(this).children()[0].innerText;
           var dateObj= $(this).children()[2].innerText;
           var temp = {
               title: titleObj,
               start: dateObj + "T" + $(this).children()[3].innerText
           };
           evs.push(temp);
       });


   console.log(evs);

   var initialize_calendar;
   initialize_calendar = function() {
            $('#calendar').each(function(){
                    var calendar = $(this);
                    calendar.fullCalendar({
                            header: {
                                left: 'prev,next today',
                                    center: 'title',
                                    right: 'month,agendaWeek,agendaDay'
                            },
                            contentHeight: 500,
                            eventBackgroundColor: '#339966',
                            eventTextColor: '#fff',
                            eventLimit: true,
                            events: evs,
                            dayRender: function (date, cell) {
                              cell.css("background-color", "#ebebeb")
                            },
                            eventBorderColor: '#339966',
                            timeFormat: 'H(:mm)'
                    });
                })
        };
   $(document).on('turbolinks:load', initialize_calendar);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css'></script>
    <title>BECK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" style = "color: white;"><b>Beck Calendar</b></a>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
             <b><%= link_to 'Home', dashboard_path %></b>&emsp;
          </li>
          <li class="nav-item">
             <b><%= link_to 'Create', new_path %></b>&emsp;
          </li>
        </ul>
        <div style = "margin-top: 8px;">
        <%= form_tag dashboard_path, :method => 'get' do %>
            <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :title => nil %>
            </p>
        <% end %>
        </div>
      </div>
  </nav>
   <%= yield %>
  </body>
</html>